name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run CI.
              run: |
                  sudo apt install valgrind tcc
                  CC=tcc   make -B
                  make check
                  export CFLAGS='-Werror -coverage -O0'
                  CC=clang make -B
                  make check
                  CC=gcc   make -B
                  make check

            - uses: codecov/codecov-action@v1
              with:
                fail_ci_if_error: true
