name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run CI.
              run: |
                  sudo apt install valgrind tcc

                  CC=tcc   make -B
                  make check

                  export CFLAGS='-Werror -coverage -O0'

                  make clean
                  CC=clang make -B
                  make check

                  make clean
                  CC=gcc   make -B
                  make check

                  make clean
                  CC=gcc   make -B
                  ./test
                  gcov str test

            - uses: codecov/codecov-action@v1
              with:
                fail_ci_if_error: true
